version: "3.8"
services:

  # proxy:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-proxy
  #   depends_on:
  #   - service-haproxy
  #   ports:
  #   - 10000:10000

  service-haproxy:
    build:
      context: haproxy
      dockerfile: Dockerfile-haproxy
    depends_on:
    - service-squid
    hostname: service-haproxy
    # ports:
    # - 3129:3129


  service-squid:
    build:
      context: squid
      dockerfile: Dockerfile-squid
    depends_on:
    - service-https
    hostname: service-squid
    ports:
    - 3129:3129
    - 3128:3128

  service-https:
    image: mendhak/http-https-echo
    hostname: service-https
    environment:
    - HTTP_PORT=0